CREATE TYPE TASK_ACTION AS ENUM ('assignment', 'change_status', 'note');

ALTER TABLE task_comments ALTER COLUMN user_id SET NOT NULL;

CREATE TABLE IF NOT EXISTS action_histories (
  task_id UUID NOT NULL CONSTRAINT fk_tasks REFERENCES tasks (id) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  action TASK_ACTION NOT NULL,
  description VARCHAR NOT NULL,
  user_id UUID NOT NULL CONSTRAINT fk_users REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE
);