CREATE TABLE IF NOT EXISTS assets(
  id UUID PRIMARY KEY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  s3_key VARCHAR NOT NULL,
  public BOOLEAN NOT NULL,
  filename VARCHAR NULL
);

ALTER TABLE tasks DROP COLUMN filename;
ALTER TABLE tasks ADD COLUMN asset_id UUID NOT NULL CONSTRAINT fk_assets REFERENCES assets (id) ON UPDATE CASCADE ON DELETE CASCADE;