ALTER TABLE tasks DROP COLUMN user_id;

CREATE TABLE IF NOT EXISTS user_tasks (
  task_id UUID NOT NULL CONSTRAINT fk_tasks REFERENCES tasks (id) ON UPDATE CASCADE ON DELETE CASCADE,
  user_id UUID NOT NULL CONSTRAINT fk_users REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE
);